In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("Final Data.csv")

In [4]:
df

,house_id,area_sqft,bedrooms,bathrooms,location_score,age_years,distance_city_km,lot_size_sqft,has_garage,has_pool,renovation_years_ago,house_price_inr
0,100210.95,1973,5,4,7.6,23.0,11.9,5220.00,1,0,0,40275084.00
1,100210.95,1560,3,3,6.3,13.0,15.8,3882.00,1,0,13,26812029.00
2,100210.95,2071,4,3,5.8,9.0,21.1,4488.00,0,0,9,29315677.00
3,100210.95,2640,5,3,7.7,12.0,7.9,3614.00,1,1,4,46250249.55
4,100210.95,1498,3,3,3.8,15.0,24.0,2663.00,0,0,15,17724566.00
...,...,...,...,...,...,...,...,...,...,...,...,...
4195,103990.05,1328,4,2,4.9,21.0,19.6,2606.00,1,0,21,18319188.00
4196,103990.05,2363,6,4,6.9,50.0,24.9,4013.00,1,0,14,40340976.00
4197,103990.05,632,2,2,4.5,27.0,19.4,1268.00,1,0,6,6189628.85
4198,103990.05,606,2,2,7.5,26.0,11.6,1026.75,0,0,9,7916191.00
4199,103990.05,2021,4,3,6.8,25.0,12.5,2351.00,1,1,4,34319843.00

In [5]:
df.columns

Index(['house_id', 'area_sqft', 'bedrooms', 'bathrooms', 'location_score',
       'age_years', 'distance_city_km', 'lot_size_sqft', 'has_garage',
       'has_pool', 'renovation_years_ago', 'house_price_inr'],
      dtype='object')

In [6]:
df = df.drop(columns=["house_id","age_years","has_garage","has_pool"])

In [7]:
df.head()

,area_sqft,bedrooms,bathrooms,location_score,distance_city_km,lot_size_sqft,renovation_years_ago,house_price_inr
0,1973,5,4,7.6,11.9,5220.0,0,40275084.00
1,1560,3,3,6.3,15.8,3882.0,13,26812029.00
2,2071,4,3,5.8,21.1,4488.0,9,29315677.00
3,2640,5,3,7.7,7.9,3614.0,4,46250249.55
4,1498,3,3,3.8,24.0,2663.0,15,17724566.00

In [8]:
df.shape

(4200, 8)

In [9]:
df.tail()

,area_sqft,bedrooms,bathrooms,location_score,distance_city_km,lot_size_sqft,renovation_years_ago,house_price_inr
4195,1328,4,2,4.9,19.6,2606.00,21,18319188.00
4196,2363,6,4,6.9,24.9,4013.00,14,40340976.00
4197,632,2,2,4.5,19.4,1268.00,6,6189628.85
4198,606,2,2,7.5,11.6,1026.75,9,7916191.00
4199,2021,4,3,6.8,12.5,2351.00,4,34319843.00

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4200 entries, 0 to 4199
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   area_sqft             4200 non-null   int64
 1   bedrooms              4200 non-null   int64
 2   bathrooms             4200 non-null   int64
 3   location_score        4200 non-null   float64
 4   distance_city_km      4200 non-null   float64
 5   lot_size_sqft         4200 non-null   float64
 6   renovation_years_ago  4200 non-null   int64
 7   house_price_inr       4200 non-null   float64
dtypes: float64(4), int64(4)
memory usage: 262.6 KB

In [11]:
df.describe()

,area_sqft,bedrooms,bathrooms,location_score,distance_city_km,lot_size_sqft,renovation_years_ago,house_price_inr
count,4200.000000,4200.000000,4200.000000,4200.000000,4200.000000,4200.000000,4200.000000,4.200000e+03
mean,1660.486905,3.651667,2.817857,5.616786,18.118810,3318.852262,7.658333,2.336096e+07
std,589.997259,1.491213,1.131259,2.061211,8.138532,1501.483812,6.447485,1.131691e+07
min,606.000000,1.000000,1.000000,1.900000,4.000000,1026.750000,0.000000,6.189629e+06
25%,1226.750000,3.000000,2.000000,4.000000,11.800000,2122.500000,2.000000,1.425969e+07
50%,1660.000000,4.000000,3.000000,5.700000,17.800000,3188.000000,6.000000,2.214500e+07
75%,2084.250000,5.000000,4.000000,7.300000,24.200000,4364.250000,12.000000,3.096090e+07
max,2735.000000,6.000000,5.000000,8.900000,32.800000,6380.200000,22.000000,4.625025e+07

In [12]:
x = df.drop(["house_price_inr"],axis=1)
x

,area_sqft,bedrooms,bathrooms,location_score,distance_city_km,lot_size_sqft,renovation_years_ago
0,1973,5,4,7.6,11.9,5220.00,0
1,1560,3,3,6.3,15.8,3882.00,13
2,2071,4,3,5.8,21.1,4488.00,9
3,2640,5,3,7.7,7.9,3614.00,4
4,1498,3,3,3.8,24.0,2663.00,15
...,...,...,...,...,...,...,...
4195,1328,4,2,4.9,19.6,2606.00,21
4196,2363,6,4,6.9,24.9,4013.00,14
4197,632,2,2,4.5,19.4,1268.00,6
4198,606,2,2,7.5,11.6,1026.75,9
4199,2021,4,3,6.8,12.5,2351.00,4

In [13]:
y = df["house_price_inr"]
y

0       40275084.00
1       26812029.00
2       29315677.00
3       46250249.55
4       17724566.00
           ...
4195    18319188.00
4196    40340976.00
4197     6189628.85
4198     7916191.00
4199    34319843.00
Name: house_price_inr, Length: 4200, dtype: float64

In [14]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [15]:
x_train

,area_sqft,bedrooms,bathrooms,location_score,distance_city_km,lot_size_sqft,renovation_years_ago
2417,1871,6,4,6.4,9.6,4867.0,0
3827,1967,4,3,7.6,12.9,4347.0,15
239,2204,5,3,2.4,22.0,5179.0,6
3633,2134,5,4,3.6,21.5,3634.0,6
1543,1353,2,3,5.6,25.7,2574.0,16
...,...,...,...,...,...,...,...
3444,2102,5,4,3.8,24.2,4162.0,2
466,2049,4,3,4.3,26.5,4248.0,22
3092,1589,3,3,4.8,19.0,1687.0,0
3772,1142,2,1,3.1,26.1,1798.0,1
860,1782,4,2,5.0,11.3,3215.0,2

In [16]:
x_test

,area_sqft,bedrooms,bathrooms,location_score,distance_city_km,lot_size_sqft,renovation_years_ago
1743,2405,4,2,6.6,10.1,3645.0,1
2196,1927,4,3,6.7,24.9,5053.0,0
1728,1889,5,4,2.5,32.8,4215.0,11
3337,1553,2,3,8.2,8.4,3059.0,2
298,2178,3,2,3.1,32.8,3459.0,17
...,...,...,...,...,...,...,...
152,1208,2,2,8.9,12.2,2519.0,6
1948,2382,4,4,7.3,18.9,4712.0,0
2751,2672,6,5,2.6,32.8,6380.2,0
2148,1583,3,2,5.1,25.0,4183.0,15
102,1427,2,3,7.0,4.0,3147.0,11

In [17]:
y_train

2417    28039339.0
3827    36655898.0
239     19744745.0
3633    21812311.0
1543    19444280.0
           ...
3444    19409041.0
466     23372689.0
3092    22461733.0
3772     8848343.0
860     21331055.0
Name: house_price_inr, Length: 3360, dtype: float64

In [18]:
y_test

1743    36890986.0
2196    27836840.0
1728    15321534.0
3337    30812774.0
298     18194835.0
           ...
152     20918771.0
1948    44375916.0
2751    22099538.0
2148    22898162.0
102     26744300.0
Name: house_price_inr, Length: 840, dtype: float64

In [19]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
pipline = Pipeline([("Scalar:",StandardScaler()),("Multiple Linear:",LinearRegression())])

In [20]:
pipline.fit(x_train,y_train)

Pipeline(steps=[('Scalar:', StandardScaler()),
                ('Multiple Linear:', LinearRegression())])

In [21]:
y_pred = pipline.predict(x_test)

In [22]:
y_pred

array([37204678.63372695, 30254882.17544862, 16348036.19161247,
       30381480.16902525, 20940877.74232021, 29652686.08420467,
        7971963.64865784, 40225945.31426522, 20559027.92620124,
       38304675.55606753, 25214032.90144372, 14717512.48714304,
       20434974.25493601, 16864512.86252296, 15892740.24299806,
       32163815.27858066, 26445556.39779491, 11493049.02250059,
       33767703.78923211, 44154168.79115766, 25975565.53160521,
        2823174.01830193, 32217902.52025851, 42206809.03053686,
       28184673.79909146, 21494912.3316848 , 30943811.17084053,
       12439912.75633959, 35752216.0705563 , 17164577.19871905,
       42542259.31145579, 28812006.55214497, 25087693.96904458,
       26430253.7240448 , 24545438.38159551, 22691344.62025627,
       22227535.05882253, 16294365.74855506, 36227860.38212599,
       16733406.47305902, 18975627.10571501, 18687611.71921144,
       24354047.68591637, 23809415.3555935 , 40642905.11566029,
       28158762.88661548, 20635852.45246067, 35088667.47485658,
       37108924.66348349, 17068559.85390883, 40536396.08957697,
       30873934.63558877, 25007403.5934686 , 23549830.5073355 ,
       27712285.30661627, 25044637.82000496, 22372984.24369345,
       29517300.72272674, 14776792.93019784, 47829463.60297939,
       30053738.88824302, 21076842.78803682, 15503734.28630122,
       43201641.06650485, 36409354.99714331, 20616000.21333692,
       23883224.11681897, 19036022.85476246, 18917712.53853466,
       18850077.74873837, 41044310.92830338,  8098688.28351006,
       35050103.63292983,  8215385.79106929,  1715037.4224008 ,
        2420032.91172725, 12578708.56670783, 32963188.56038988,
       18293449.3728973 ,  8239838.60800609, 24539569.32497445,
       37353174.60749226, 28515349.08763842, 14912056.63276424,
       31581817.00301822, -3890789.33104981, 25828547.47908091,
       40659654.18967255,  8314212.00915799, 35024594.53043168,
       33713963.38389269,  7604124.09409494, 22388289.23519772,
       13251740.92302721, 36251483.58693446, 31723347.98338136,
       18444034.20154712, 15599065.538714  , 35768869.24615751,
       26047873.55909795, 22876425.37921519, 14999913.02167743,
       33900449.57814689, 30845030.15363309, 19915256.84837038,
       16436262.88731515, 17398270.73189101, 23854993.65942534,
       22150887.00649658, 28410884.56468224, 12165829.21942635,
       29002617.31503427, 19500291.37236951, 38567516.72605862,
       36475384.42948672, 39944084.35696524, 31433913.40295338,
       26660900.71485194, 26133105.07458323, 19411166.49148161,
       21736410.83303676, 28290801.91127069, 30003570.78434837,
       33629833.85926136, 32352695.43445359, 26402861.6034351 ,
       21735803.50332676, 28033987.57433554, 41897094.06753254,
       28542936.35602384, 41497024.18773191, 15168329.07746598,
       16001839.80886691, 13656945.80234141,  5206502.68363065,
       33249615.30815899, 32926537.63205463, 30465292.43396525,
       33049747.83849248, 24278057.00406528, 13634305.76579111,
       36699427.79092685, 42314310.52821656, 15082067.31675841,
       17553672.3487724 , 15770654.85714586, 14818520.40812798,
       17921578.60770113, 29346809.19776531, 23626553.42953532,
       13151174.71990849, 20912897.09026185, 14570732.74031861,
       33365245.61364823, 29726480.59881089, 13983712.5470089 ,
       40343738.06394997, 26620193.24688274, 30507686.06692249,
        7164458.85803159, 28170546.1128308 , 27577539.8801573 ,
       38321644.13358934, 39232602.81376545, 18612380.22747499,
       33118323.65275314, 12050610.72416454, 21822318.33603711,
       21733290.20918941, 36670848.61631352, 38137327.34148693,
        5304762.72525908, 25642166.4001791 , 21843034.74649312,
       29361932.29244673, -1206916.93603536, 24095897.97720602,
       13171097.45173551, 32621277.02693056, 13755686.75155471,
       31306717.96751818, 41141908.71428309, 18321719.14518836,
       18604994.3790156 , 36774642.85239948, 31887107.50830778,
        4465886.16559052, 30446081.47727213,  3650548.32378775,
       27179698.69191619, 23233850.81044242, 31701407.37668063,
       33045988.04921668, 15440681.16183461, 10247878.57597867,
        -916777.71123569, 25788158.590619  , 23156594.65453613,
       34019041.21597452, 23770415.6764074 ,   240156.39327814,
       12988704.5189748 , 24884267.51627148, 44181776.30134247,
       11378396.58939928, 34016685.50731599, 27190955.05729757,
       26408435.0268787 , 16382872.46580514, 30016491.69696016,
       34807690.65804558, 11972413.04498894, 14996875.97628636,
       29064865.56276955, 22024304.90915366, 24755840.87789021,
       22741437.12321513, 19297082.11760081,  5630319.82878659,
       24430263.93637817, 28286617.83792664, 24064699.38179802,
       10663973.48230819, 18868043.72399223, -1775438.27704534,
       23300733.53927896, 32233346.83685277, 15765826.35456763,
       25855313.73952907, 25315346.4703211 , 19036583.11690706,
       18047684.24850755, 25052720.34312787, 18318730.81349829,
       14114414.66096518, 27371842.81907564, 23662655.1852197 ,
       33693709.0848704 , 17515925.49118089, 19359720.67353128,
       17506319.54312113, 31025079.30383032,  9757729.63150649,
       32179320.12942412, 21012270.44291027, 19138558.61715627,
       21296557.16663682, 32816262.66564483, 28948125.13725688,
       34219855.28039491, 16170995.42837783, 18953368.86839238,
       26074162.64702785, 20285844.78939984, 21545620.7710411 ,
        4788339.82486577, 25988288.10755954,  7376760.92841798,
        5751316.3875771 , 46908781.7003236 , 29195768.54014466,
       23093488.63164848, 24466902.1798305 , 34930885.38535812,
       29997241.61120483,  4228463.4809746 , 31860833.54643306,
       21183839.27904905, 23320670.48270232, 15072658.55642813,
       28622545.6083579 , 40603690.24721394, 24235899.71547291,
       40932703.89673404, 20419780.11397652, 28414034.89250119,
       10386840.29076494, 27387963.34913677, 12496373.82586168,
       29127153.47691253, 43387836.35987639, 12209770.81290755,
       36782811.63957787, 17225139.04297369,  1988111.20711503,
       25968201.26393002,  4716113.34040678,  6648360.73277629,
       33125862.6066943 , 20341150.30530418, 31727586.95527365,
        8033335.10309313, 16570482.30372825, 38524652.91338603,
       10860294.43140199, 18459516.83318937, 28111324.49090349,
       18286010.87004887, 24751476.46912561, 25545461.95648507,
       39639289.17418654, 26335521.0116652 , 28212563.86446832,
       26806428.90344175,  4746606.24316753, 44600180.94033881,
       34925021.56554432, 24274135.0209476 , 23749176.07727716,
       30743448.82938741, 35908787.21276066, 29632684.71831601,
       23663567.39225916, 29355629.0086325 , 19532602.67330528,
       17115018.41323113, 18596662.88098502, 37520214.67914744,
       19976650.68673525, 13493114.17316724, 29716407.06033215,
       27487403.37307997, 19047543.82013878, 16487332.99627855,
       16898577.65956985,  9291957.33985071, 33881831.65574065,
        6475747.10603258, 21447086.00794509, 22932966.88740943,
       24791827.08106198,  9979065.68085329, 35651588.19597889,
       34418288.86457866, 29183412.57540336, 34728604.34441007,
       36506113.57770596, 18667255.22839307, 32863930.53133118,
       16050829.73065178,  8379949.76424899, 27851012.90492072,
       17489523.43407372, 16077720.05948624, 18641712.01188244,
       28321557.25582757, 11571387.00718061, 26035817.52319872,
       34163346.24038991, 16044314.19334247, 25044138.96726828,
       39409746.26962306, 44508828.15202495, 37358574.74381753,
       19242835.63158347,  2775976.18952582, 30920232.30418269,
       38694356.9709741 , 13408125.34661899, 37561532.69754641,
       16234734.8379963 , 18495663.35221611, 36807949.41438511,
       18927471.06725821, 13141203.10684274, 26198754.15740486,
       20178698.42405882, 38995761.12416053, 32281398.92213592,
       14561754.43221727, 21483318.32479132, 25448300.92379096,
       35532844.43100304, 23637762.44653881, 27692078.91875554,
       28581161.88821364, 14326483.95275364, 24525342.4704388 ,
        8991599.98715555, 14794443.05163484, 32723684.04637489,
       48472101.36730695, 29668225.39509058, 37831725.69092994,
       39003381.8499644 , 11531335.66782524, 20382398.42982012,
       38780882.95922343, 25404027.15309976,  -110804.43911467,
       30578442.23719404, 37815954.75495792, 32285399.99439947,
       28094397.57464059, 23169238.13241935, 30059290.01847444,
        9418139.94038659, 20429749.54512696, 21952320.64158981,
        4735945.88822249,  8307421.26020184, 39507495.53982271,
       14574753.7464088 , 29098962.67211949, 10676503.61161742,
       35012251.19591174, 38019390.86555442, 29215891.08298572,
       25202431.4505861 ,  9538294.68629303, 22248053.17736362,
       24139683.02108595, 36824748.95644207, 47094841.50452219,
       26583026.78116874, 17558028.27077935, 21949911.72474662,
       36647676.28727844, 49901150.22621939,  6982810.67963123,
       11787390.50328823,  7745430.37951262, 36715525.05972653,
       21099105.09290926, 13537132.97834327, 34661877.06015877,
       19175319.14870739, 25269598.50570815, 26432036.06249329,
       13673429.77137657, -1689092.74179957, 43716771.64328035,
        9997251.61682412, 19241210.79067801, 30995439.485031  ,
       37697415.9212724 , 10860804.37152752, 23938751.10098205,
       12244404.11086086,  5854878.96157352, 33671052.208774  ,
       17794513.34547197, 20500105.68700903, 11589383.4078931 ,
       18899388.13114557, 32319117.6117002 , 39838240.67608994,
       45926874.66130821, 45226519.6431911 , 11908457.40627961,
       19945157.60690819, 24304497.54203164, 24372059.1314542 ,
       37960678.33504406, 15590416.8428816 ,  9931356.35477167,
       16727013.62776549, 28677598.33103967, 16626320.31120949,
       17017190.8878172 , 27980292.70616579, 28556378.79454634,
        -834614.44212028, 15987128.00303592, 26004069.78986773,
       36682798.4215687 , 14043028.89143982, 28664456.80208898,
       12443002.47755609, 17587836.73326736, 22703695.91663709,
       25721221.86791788, 35564564.39161555, 33220435.20001846,
       17746736.84597366, 37726134.47220754, 20331729.64734849,
       14398650.01527704, 29503403.20462729, 37929689.86421358,
       19091408.33429226, 27326067.2537806 , 25216222.38497812,
       27470635.42176431,  6457206.44654979, 15705843.33418155,
       35810924.21537682, 13671928.76660116, 34520751.75593835,
       24998620.22292467, 15121032.74897866, 29189274.36604483,
        7305272.08216749, 12998967.00293829, 27398333.53064317,
       26792822.34288215, 40332947.18087779, 24713679.72421872,
       18113698.34930614, 29554410.54671019, 24841345.46646377,
       29654670.39345529, 23881454.9143156 , 10897591.46819446,
       22132148.62010801, 15688483.26739326, 36720982.06957931,
       28046541.70702543, 35206994.32915021, 26533989.77572336,
        2947057.23752905, 20799387.75534188,  3027706.72134534,
        8486669.40240057,  9871493.95205221, 13594793.69666641,
       13305263.77183195, 30054694.80803534,  6618489.72453122,
       25719947.64965279, 47589879.68396403, 11209515.96920772,
       21521695.47168179, 25069693.98424966, 13743673.4850322 ,
       11171060.69264545, 16710016.28856837, 22650964.81876215,
       39214340.4137182 , 16361782.98270886, 23922044.45843253,
        9383753.98840844, 17520313.6170601 , 41406982.45844555,
       31314664.24340702, 16719439.09261522, 29238754.62835655,
       20031825.74139357, 16533724.76102818, 25325657.25730574,
       18747631.95417885, 15589803.37935293, 32556060.19038596,
       12404978.41151276, 19299910.38499098, 25134089.87670711,
       28100943.63207225, 28329999.70938058, 29861823.12328032,
       15764712.28819839, 24693134.33461312, 30423868.95872536,
       23933922.75786512, 10760852.78684516, 13096543.69317378,
       21924590.28190466, 34857531.20242729, 36842193.7809998 ,
       12764585.75255848, 18006888.44746229, 49655798.49452502,
       30840441.94465917, 12847696.43065755, 23750682.62100308,
       15039127.3558924 , 15097564.97541738, 27145046.29666404,
       12048120.87530182, 25612358.5585518 ,  8801784.60070502,
       27265680.8344087 , 33575591.41821364, 19399395.675859  ,
        7013254.60190923, 23232092.20909894, 19381313.1182618 ,
       36817651.39647582, 27914966.96701909,  6644174.47287001,
       28162458.91300825,  3836198.9459273 , 14511845.94147402,
       27794251.23053166, 12434021.24011808, 33933920.73189157,
       28625013.7049944 , 41106255.69398022, 27906486.18639794,
       29592341.89381698, 13497722.77106753, 45781294.44515851,
       36479699.36998136, 17543173.66862506, 25756247.72702234,
       19785529.9836454 , 16920017.91672377, 26016966.21480546,
       34298301.3109159 , 12403747.28846201, 18851199.61848954,
       19221982.79267557, 15183875.75194991, 22926016.91323038,
       28826206.94949468, 34470223.70173457, 38398088.26359169,
       29356188.62646747, 30692523.61028994, 23366701.53450142,
       40715908.64632967, 17642616.76650352, 28792838.12907499,
       45345579.90611644, 32838578.81981502, 38394900.45192309,
       13304929.87196845, 25196012.89533982, 17042740.96126141,
       21819203.75624464, 35024235.73296262, 25376434.45603114,
       43375179.6875961 , 26161976.11657452, 22900961.75156844,
       24905669.6618038 , 11424344.65911799, 17441615.5436568 ,
       10810888.1186293 , 34590058.2785809 , 34780078.66763794,
       19261655.47273287, 19279352.45825045, 31211939.43620025,
       -2297398.2705576 , 28836551.4811784 ,  5633609.91082191,
       25576819.28289895, 19221215.93038012, 12565367.75656269,
       25737604.58896954, 18477190.02639753, 23790753.69000049,
       21142399.57286107,  7654648.09292662, 15702252.95361526,
       15047990.68957837, 21291826.26926976, 23391776.89004262,
       20077574.35188349, 34431184.78500964, 25396439.48403764,
       12873123.08305998, 28943302.66443464, 18044804.8903479 ,
       38160239.89788629, 33481324.99224445, 36811574.24848542,
        2330462.34212524, 28607466.29752152, 27818861.50065539,
       17101398.79595237, 30716732.40543118,  2903608.8297993 ,
       31183258.35621605, 32218937.85627675, 26536820.31577067,
       28130139.12673134, 43569570.33055857, 16838881.56654071,
       21340058.81737256, 25656080.2706301 , 42646523.96498335,
       14915169.68224584, 36734784.92425557, 25789655.42390285,
       17320965.82138459, 37824491.97874698,  5024668.06501374,
       32173533.62387002, 31751652.70408805, 10343022.61945182,
       21407529.67502962, 12505414.40068378, 17399623.86648736,
       48271152.41329871, 20433329.68607282, 48405474.73636977,
       26699261.91921879, 25890840.10139909, 38940048.73769532,
       34753496.70037355, 14386022.75080784, 44937557.34327102,
       49397679.48857371, 39412139.41130278, 27242521.29366061,
       32625754.91632944, 15065285.68555664, 19828139.41006334,
       25890354.91137161, 31336994.41842688, 30113893.23218427,
       10610884.40383897, 22860608.09539583, 26490243.3481352 ,
       11625505.25696601, 20255209.60766579, 38474427.42568428,
       11537291.91181658, 18714375.71307867, 19373510.75294927,
       33112034.767447  , 37270865.15428752, 39852661.07441786,
       16266083.58957267, 12783004.7860173 , 38586095.8606427 ,
       23122594.17500013, 42948101.56169332, 13967657.78623519,
       32399614.04011137, 17464115.32123384, 21824809.20419772,
       19502628.26935946, 12842271.76856581,  5955942.93414702,
       34010774.51722306,  1785182.34927199, 35259679.79907095,
       20067159.60031865, 17601307.69076706, 25974613.16969847,
       36175087.6111908 , 30282570.90083665, 31520755.47016158,
       11251941.8865964 ,  8549318.84477116, 15073483.89498235,
       42664878.73721634, 17449791.54748389, 19546348.02887456,
       17801911.14780081, 28974418.10649699, 19943944.06490842,
       13230602.11922036, 27174107.48867472, 17995462.94580773,
       35548066.71430755, 21496960.76588615,  8661876.4628133 ,
       21965753.24053212,  4072334.72849924, 21097054.74793643,
       14848228.90294705, 22078745.74744388, 20853497.21442852,
       26663160.21706335, 34151513.14050017, 17294695.41054582,
       16522188.57209628, 26038273.2570713 , 14577259.02073639,
       15071365.5418637 , 26240703.60471731, 44665118.83284582,
       21576569.54625281, -3944426.83377673, 10691287.69296383,
       38769548.66147684, 42579777.71866092, 18568835.83975594,
       21540458.3215371 , 26936117.00947216, 12556266.48020541,
       31058610.38020838, 38901737.78656001, 45207646.77756241,
       22511998.16249748, 28417307.0870194 , 17353786.82562542,
       35758975.58728692, 26986354.57611708, 17010558.94408409,
       15564403.43363786, 20802613.58339623, 21919118.47595925,
       15049520.94602925, 29785268.3658011 , 18643830.07882519,
       27757868.31043355, 29253110.27100865, 19141397.17005286,
        7256211.95486688, 18850584.65884323, 12098669.77062111,
       35268730.55912403, 15440906.25448597, 38742066.26558172,
       28558330.27459147, 33285117.69155466, 20378165.77435322,
       26309505.16008967, 19013293.00273988, 38666546.42792822,
       30120648.9535924 , 21925958.79995647, 23627481.90969878,
       19860474.54324044, 44228977.99441729, 32424900.64373801,
       37442640.02643324, 29359768.42146383, 33047199.27901112,
       24120385.18438002,  5250297.68574734, 22311111.24359217,
       20490568.21687466, 20166992.34958629,  6007141.57788156,
       27991046.76037037, 25561090.35861911, 11999109.1566877 ,
       31074347.23258072, 26739991.36504272, 27589514.27005123,
       42447926.81247207, 13100418.4003547 , 26392374.05402264,
       28058047.76050343, 33813908.08173649,  1348287.60590072,
       45660886.93466596, 21830855.69534315, 27827610.582147  ,
       12421733.16515446, 27089585.7589137 , 38722330.63793384,
       28266359.45179281, 19853451.41459389, 25226846.35037614])